export const GET_ALL_CHARACTERS_REQUEST =
  '@character/GET_ALL_CHARACTERS_REQUEST';
export const GET_ALL_CHARACTERS_SUCCESS =
  '@character/GET_ALL_CHARACTERS_SUCCESS';
export const GET_ALL_CHARACTERS_FAILURE =
  '@character/GET_ALL_CHARACTERS_FAILURE';

export const SELECT_CHARACTER = '@character/SELECT_CHARACTER';
export const DESELECT_CHARACTER = '@character/DESELECT_CHARACTER';
